import type { Metadata } from "next";
<<<<<<< HEAD
import { Urbanist } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-urbanist",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
=======
import { Inter } from "next/font/google";

import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Public Domain Art Gallery",
    template: "%s | Public Domain Art Gallery",
  },
  description:
    "Browse timeless public domain artworks by style, artist, and period. Free and open art references for study and inspiration.",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-50 text-neutral-900`}>
        <Header />
        <main className="mx-auto w-full max-w-6xl px-6 py-10">{children}</main>
>>>>>>> 42d7ea5 (initial commit)
      </body>
    </html>
  );
}
